### ISSUE TITLE
Some Questions!

### ISSUE THREAD

**Issue by dazinator** [alexurquhart/hugo-geo#13]
Hello,

I have tried to get up and running with this theme, and I have hit problem, most likely due to my lack of experience with hugo.

When you hit the default landing page of my site, I can't figure out how to place some content there - similar to your website I'd like it show recent blog posts by default. At the moment it shows this:

![image](https://cloud.githubusercontent.com/assets/3176632/21742470/dd9644ac-d4e7-11e6-8a7e-020a5954e696.png)

I have to click on the "Blog" link to then navigate to posts!

My second problem is that when I navigate to a post, it doesn't seem to display any tags..

Here is my yaml front matter:

```
---
title: Unit Testing Dynamics CRM Plugins
date: 2014-12-14T17:50:00
comments: true
categories: 
    - "Dynamics CRM"
published: true
tags:
    - "Unit Testing"
---
```
And here is what I see in the browser (no tags showing)

![image](https://cloud.githubusercontent.com/assets/3176632/21742518/9509b286-d4e8-11e6-9e78-b893f06c8144.png)

Not quite sure where I might be going wrong!

**Comment by Pofilo** [comment]
You should put your content into the folder: `yourSite/content/post/`

With that, you will normally be able to see the resume of the article on your index page.

Moreover, if you look at the [example site](http://alexurquhart.github.io/hugo-geo/post/welcome/), you'll see that there is no tags on this page. So it means that @alexurquhart is running a version different from the one on github.

Did I answer your questions ? :)

**Comment by dazinator** [comment]
Thank you! Yep, my posts were in a "posts" folder, moving them to "post" has solved it :-)

Tags do show up on list view, so this is good enough for me!

Cheers
