### ISSUE TITLE
Rss links / social media buttons

### ISSUE THREAD

**Issue by dazinator** [alexurquhart/hugo-geo#14]
Just a couple of suggestion, how about adding the ability to share post to various social media - i.e Facebook, Twitter, Linked In etc etc.

Also the ability to display as RSS icon for people that want to subscribe to an RSS feed.

**Comment by alexurquhart** [comment]
I'm currently working on a v2.0 of the theme, and am looking to include something like [these](http://huacnlee.com/social-share-button/) icons, configurable on a page-by-page basis.

**Comment by dazinator** [comment]
Amazing! I'll happily give that a go once it's ready :-)
Thank you for all the work you have put into this theme.

**Comment by dazinator** [comment]
How did you get on - is this in version 2 now?
