### ISSUE TITLE
Client-side high CPU usage due to globe script

### ISSUE THREAD

**Issue by cvax** [alexurquhart/hugo-geo#20]
When we have the globe script running and have the tab open in Chrome, it pegs one of our client CPU cores to max. I never paid attention to this if it happened before, but definitely noticed it now.

**Comment by alexurquhart** [comment]
I've tested on my machine adding an interval of ~100 ms to the d3.timer call in App.js, but it doesn't let my CPU get below 40%. Any more delay and the animation begins looking choppy. 

If you don't want the globe to spin, you can comment out the call to `d3.timer` in App.js, and the globe will render, but not spin. You can also set `showglobe=false` in your site config.toml to have the globe removed entirely. Right now the animation is turned off for mobile devices, so the impact should be limited to desktops.
