### ISSUE TITLE
How can I add image on my blog post 

### ISSUE THREAD

**Issue by shohan4556** [alexurquhart/hugo-geo#28]
please tell me how can I add image on my blogpost and tutorial

**Comment by alexurquhart** [comment]
Right now I'm just using `<img>` tags in the markdown. The theme is based off Bootstrap v3, so helper classes for alignment, etc can be used.

In the next iteration of this theme there will be shortcodes for images,.

**Comment by shohan4556** [comment]
Hello I am trying these `image = "img/shohan.png" and
![](img/shohan.png)` but nothing work. can you please share how you add image ?

**Comment by alexurquhart** [comment]
You would use something like `<img src="img/shohan.png">` inside your content markdown
