### ISSUE TITLE
Fix post slug?

### ISSUE THREAD

**Issue by 7MinSec** [alexurquhart/hugo-geo#4]
Hi there,

I'm super newb to Hugo but really like your theme and am playing with it on a dev site.  Right now my prod site's slugs are http://site.com/name-of-post.  When I enable your theme on my dev site, it adds "post" so my links are http://site.com/post/name-of-post.  What can I tweak so that my hierarchy goes back to site.com/name-of-post?

Thanks,
Brian

**Comment by alexurquhart** [comment]
Hey Brian,

The list of content for the index page is generated in the layouts folder in [index.html](https://github.com/alexurquhart/hugo-geo/blob/master/layouts/index.html#L8)

If you replace that range statement with with: `{{ range .Data.Pages }}`, it should iterate over all the pages on your site.

**Comment by 7MinSec** [comment]
Thanks for the quick response.  Ok this change seems straight forward enough but it's still leaving the "post" as part of the URL.  Does this look right? ([index](index.html)) is on the left and my change on the right.

Brian

<img width="796" alt="geo" src="https://cloud.githubusercontent.com/assets/17596787/18015905/4acb7a82-6b8f-11e6-83bd-8a93f2c7ba1c.png">

**Comment by alexurquhart** [comment]
Is your markdown content inside a `post` directory? If you create new content in the root of the `content` folder it should show up.

**Comment by 7MinSec** [comment]
I'll give that a shot - thanks!
