### ISSUE TITLE
Please switch to safe baseURL for example config

### ISSUE THREAD

**Issue by digitalcraftsman** [alexurquhart/hugo-geo#6]
Apparently a scammer has registered the default base url genreated by hugo ("http://replace-this-with-your-hugo-site.com") and has some malware, ads, etc on it. See: spf13/hugoThemes#171.

To avoid such abuse in the future I would recommend to switch to a base url like "https://www.example.com/".

Thanks

**Comment by Pofilo** [comment]
Thanks for the tip, i changed it in my theme ! 👍 
It's crazy to see people doing things like that 👎

**Comment by alexurquhart** [comment]
Thank you for letting me know, the example theme has been fixed!
